name       : libmikmod2
version    : 3.1.21.1
release    : 1
source     :
    - https://excellmedia.dl.sourceforge.net/project/mikmod/libmikmod/3.1.21.1/libmikmod-3.1.21.1.tar.gz : 1a88922b5a67c308899c1d991ddfb62b5d851f8a94175612b33856854938b2fb
license    :
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : binary.compat
emul32     : yes
summary    : Portable sound library
description: |
    This package provides binary compatibility only. It is forbidden to build against it.
builddeps  :
    - pkgconfig32(alsa)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    # Only include the library
    for i in /usr/bin %libdir%/pkgconfig /usr/include /usr/share %libdir%/libmikmod.so; do
        rm -rfv "$installdir/$i"
    done
